version: "3"
volumes:
  vendor_bundle:
  node_modules:

services:
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/teikitenkenyosi/public
      - tmp-data:/teikitenkenyosi/tmp
    ports:
      - 80:80
    depends_on:
      - rails

  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/teikitenkenyosi
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /teikitenkenyosi/log
      - /teikitenkenyosi/tmp
      - vendor_bundle:/teikitenkenyosi/vendor/bundle
      - node_modules:/teikitenkenyosi/node_modules
    # tty: true
    # stdin_open: true
    command: bundle exec puma -C config/puma.rb -e production
