version: "3"

services:
  nginx:
    build:
      context: containers/nginx
      dockerfile: dockerfile
    volumes:
      - public:/teikitenkenyosi/public
      - log:/var/log/nginx
      - tmp:/teikitenkenyosi/tmp
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails

  rails:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    env_file:
      - .env
    volumes:
      - .:/teikitenkenyosi
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /teikitenkenyosi/log
      - /teikitenkenyosi/tmp
      - storage:/teikitenkenyosi/storage
      - vendor_bundle:/teikitenkenyosi/vendor/bundle
      - node_modules:/teikitenkenyosi/node_modules
      - tmp:/teikitenkenyosi/tmp
    tty: true
    stdin_open: true
    command: >
      bundle exec rails webpacker:install
      bundle exec rails db:create -e production
      bundle exec rails db:migrate
      bundle exec puma -C config/puma.rb -e production      
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - .env
    networks:
      - default
    ports:
      - '33406:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  storage:
  mysql_data:
  vendor_bundle:
  node_modules:
  public:
  log:
  tmp:
