version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  storage:

services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    networks:
      - default
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/teikitenkenyosi
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /teikitenkenyosi/log
      - /teikitenkenyosi/tmp
      - vendor_bundle:/teikitenkenyosi/vendor/bundle
      - node_modules:/teikitenkenyosi/node_modules
      - storage:/teikitenkenyosi/storage
    tty: true
    stdin_open: true

    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    command: bash -c "bin/dev"
