version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  storage:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33406:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/teikitenkenyosi
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /teikitenkenyosi/log
      - /teikitenkenyosi/tmp
      - vendor_bundle:/teikitenkenyosi/vendor/bundle
      - node_modules:/teikitenkenyosi/node_modules
      - storage:/teikitenkenyosi/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
