version: "3"

services:
  nginx:
    build:
      context: containers/nginx
      dockerfile: dockerfile
    volumes:
      - public:/teikitenkenyosi/public
      - log:/var/log/nginx
      - tmp:/teikitenkenyosi/tmp
    ports:
      - 80:80
    depends_on:
      - app

  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.deploy
    image: sm030330/tenkenchecker-app:latest
    env_file:
      - .env
    volumes:
      - .:/teikitenkenyosi
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /teikitenkenyosi/log
      - /teikitenkenyosi/tmp
      - storage:/teikitenkenyosi/storage
      - vendor_bundle:/teikitenkenyosi/vendor/bundle
      - node_modules:/teikitenkenyosi/node_modules
      - tmp:/teikitenkenyosi/tmp
    tty: true
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    networks:
      - default
    ports:
      - '33406:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  storage:
  mysql_data:
  vendor_bundle:
  node_modules:
  public:
  log:
  tmp:
