FROM nginx:alpine

# インクルード用のディレクトリ内を削除
RUN rm -f /etc/nginx/conf.d/*

ADD nginx.conf /etc/nginx/conf.d/nginx.conf

# Nginxの設定ファイルをコンテナにコピー
# docker buildのときは以下のコメントをはずす
# ADD nginx.conf /etc/nginx/conf.d/tenkenchecker.conf

CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
